baseURL = "https://ckdash.com/"
languageCode = "en-us"
title = "Chandan Kumar Dash"
theme = "hugo-theme-stack"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    guessSyntax = true
    tabWidth = 4

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    author = "authors"

[params]
    mainSections = ["blogs"]
    featuredImageField = "image"

    [params.sidebar]
        avatar = "https://github.com/ckdash-git.png"
        title = "Chandan Kumar Dash"
        subtitle = "Software Development Engineer | Backend, Mobile - iOS, Go & Flutter"

    [params.colorScheme]
        toggle = true
        default = "light"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/ckdash/"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://x.com/chandankdash"
    [[params.socialIcons]]
        name = "reddit"
        url = "https://www.reddit.com/u/ck_dash/"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/ckdash-git"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/blogs/"
        weight = 2
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4
    [[menu.main]]
        identifier = "write-for-us"
        name = "Write for Internet"
        url = "/page/write-for-us/"
        weight = 5
        params = { icon = "messages" }

[permalinks]

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML"]



[params.article]
    toc = true
    readingTime = true

[params.widgets]
    [[params.widgets.homepage]]
        type = "search"

    [[params.widgets.page]]
        type = "search"
    [[params.widgets.page]]
        type = "toc"
        
[params.comments]
    enabled = true
    provider = "giscus"

    [params.comments.giscus]
        repo = "YOUR_GITHUB_USERNAME/YOUR_REPO_NAME" # Placeholder for Giscus Repo
        repoID = "" # Placeholder
        category = "Announcements"
        categoryID = "" # Placeholder
        mapping = "title"
        lightTheme = "light"
        darkTheme = "dark_dimmed"
        reactionsEnabled = 1
        emitMetadata = 0
        inputPosition = "top"
        lang = "en"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 50